server:
  port: 9001

spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      #first set "always" to init schema, then set "never",
      #otherwise the later running instances will overwrite previous instances.
      initialize-schema: always
    #      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            isClustered: true
            misfireThreshold: 120000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tomin?useUnicode=true&characterEncoding=utf-8
    username: tomin
    password: F-p6AE!om
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:tomin;DB_CLOSE_DELAY=-1;MODE=MYSQL
#    username: root
#    password:
#  sql:
#    init:
#      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql
#      mode: always
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true

springdoc:
  api-docs:
    version: openapi_3_0

cxf:
  path: /services

